import ViewTypes from "./ViewTypes";
import SummaryPos from "./SummaryPos";

export default {
  schedulerWidth: "100%",
  besidesWidth: 120,
  schedulerMaxHeight: 700,
  tableHeaderHeight: 100,

  agendaResourceTableWidth: 160,
  agendaMaxEventWidth: 200,

  dayResourceTableWidth: 110,
  weekResourceTableWidth: "16%",
  monthResourceTableWidth: 220,
  quarterResourceTableWidth: 160,
  yearResourceTableWidth: 160,
  customResourceTableWidth: 160,

  dayCellWidth: 60,
  weekCellWidth: "12%",
  monthCellWidth: 120,
  quarterCellWidth: 80,
  yearCellWidth: 80,
  customCellWidth: 80,

  dayMaxEvents: 99,
  weekMaxEvents: 99,
  monthMaxEvents: 99,
  quarterMaxEvents: 99,
  yearMaxEvents: 99,
  customMaxEvents: 99,

  eventItemHeight: 30,
  eventItemLineHeight: 24,
  nonAgendaSlotMinHeight: 80,
  dayStartFrom: 0,
  dayStopTo: 23,
  defaultEventBgColor: "#80C5F6",
  selectedAreaColor: "#F9F59F",
  nonWorkingTimeHeadColor: "#999999",
  nonWorkingTimeHeadBgColor: "white",
  nonWorkingTimeBodyBgColor: "#fff0f6",
  summaryColor: "#666",
  summaryPos: SummaryPos.TopRight,
  groupOnlySlotColor: "#F8F8F8",

  startResizable: true,
  endResizable: true,
  movable: true,
  creatable: true,
  crossResourceMove: true,
  checkConflict: true,
  scrollToSpecialMomentEnabled: true,
  eventItemPopoverEnabled: true,
  calendarPopoverEnabled: true,
  recurringEventsEnabled: true,
  headerEnabled: true,
  displayWeekend: true,
  relativeMove: true,
  defaultExpanded: true,

  resourceName: "Resource Name",
  taskName: "Task Name",
  agendaViewHeader: "Agenda",
  addMorePopoverHeaderFormat: "MMM D, YYYY dddd",
  eventItemPopoverDateFormat: "MMM D",
  nonAgendaDayCellHeaderFormat: "ha",
  nonAgendaOtherCellHeaderFormat: "ddd M/D",

  minuteStep: 30,

  views: [
    {
      viewName: "Day",
      viewType: ViewTypes.Day,
      showAgenda: false,
      isEventPerspective: false,
    },
    {
      viewName: "Week",
      viewType: ViewTypes.Week,
      showAgenda: false,
      isEventPerspective: false,
    },
    {
      viewName: "Month",
      viewType: ViewTypes.Month,
      showAgenda: false,
      isEventPerspective: false,
    },
    // {
    //   viewName: "Quarter",
    //   viewType: ViewTypes.Quarter,
    //   showAgenda: false,
    //   isEventPerspective: false,
    // },
    // {
    //   viewName: "Year",
    //   viewType: ViewTypes.Year,
    //   showAgenda: false,
    //   isEventPerspective: false,
    // },
  ],
};
